### ISSUE TITLE
Error handling/wrapping proposal

### ISSUE THREAD

**Issue by jaffee** [pilosa/general#28]
I'd like for Pilosa (as a whole) to have an official stance on error handling that we do consistently across our codebases. I'm making this issue to codify what I think we're already converging on, and gather any feedback so we can make tweaks or throw it out the window if it doesn't make sense.

Oftentimes when writing Go code (especially new code), the temptation is to handle errors by returning them wholesale:
```go
if err != nil {
    return err
}
```
This is a great first step, and about a trillion times better than ignoring the error, but it can make debugging difficult when a very low level error brings your program to a grinding halt, and all you see is "connection reset" or "no such file or directory". It's not a problem if you program has one goroutine and only opens one file, but if you're running (e.g.) Pilosa and you get that error, it's very difficult to even begin debugging. Can you even name all the places that Pilosa might open a file or directory?

I would like to propose that by default, we ALWAYS wrap any returned error with a little bit of context.
```go 
if err != nil {
    return errors.Wrap(err, "opening boltdb")
}
```

`errors` here is `github.com/pkg/errors` which is basically doing `fmt.Errorf("opening boltdb: %v", err)` but looks a bit cleaner and has a few other benefits which are described in this somewhat famous post: https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully - of which this issue is basically a summary.

So now we get `"opening boltdb: no such file or directory"`, great! Maybe we accidentally deleted or moved the bolt file, and we can grep the codebase for the string "opening boltdb" to narrow down where the error is coming from.

The downside to wrapping errors is that you can no longer match against specific error types without doing some nasty string comparison. Matching against specific types is discouraged  for reasons described in the blog post, but in the case that it becomes necessary, one can use `errors.Cause(err)` to determine the underlying concrete error value that was originally wrapped.

The obvious question now is "what context should I add to a given error?". It isn't always clear, and occaisionally the context isn't actually necessary, but the important thing to keep in mind is this: will someone looking at this error message be able to determine unambiguously where it came from? So if you have a function that might return an error in three separate places, the context that you give in each of those places SHOULD BE DIFFERENT. Also, you don't need to include the name of that function in each of these - that is the job of whatever code is calling this function and handling it's returned error. For example:

```go
func (s *Server) Open() error {
	ln, err = tls.Listen("tcp", s.URI.HostPort(), s.TLS)
	if err != nil {
		return errors.Wrap(err, "starting tcp listener")
	}
	s.ln = ln

	// Open holder.
	if err := s.Holder.Open(); err != nil {
		return errors.Wrap(err,"opening Holder")
	}

	if err := s.BroadcastReceiver.Start(s); err != nil {
		return errors.Wrap(err, "starting BroadcastReceiver")
	}

	// Open NodeSet communication
	if err := s.Cluster.NodeSet.Open(); err != nil {
		return errors.Wrap(err, "opening NodeSet")
	}
}
```
Whatever is calling Server.Open would check it's error and add some context like "opening Server". If s.Holder.Open() returns an error, maybe it occured while opening the column attribute store, and you might get something like our original example. So the whole thing would look like:
`opening Server: opening Holder: getting column attributes: opening boltdb: no such file or directory` which is basically a condensed and very readable stacktrace that tells you exactly what the program was doing when it failed.

**Comment by alanbernstein** [comment]
I find the "condensed stacktrace" messages very helpful. Losing error type matching seems like a minor drawback.

**Comment by jaffee** [comment]
you don't actually lose it if you're using `pkg/errors` @alanbernstein - you can use `errors.Cause(err)`  to "unwrap" the error and get the original back.

**Comment by travisturner** [comment]
I support this movement.
Does this obviate the need to use error codes or anything like that?
Also, how does this strategy work with the system error constants currently defined in `pilosa.go`?
```
...
ErrFrameExists          = errors.New("frame already exists")
ErrFrameNotFound        = errors.New("frame not found")
ErrFrameInverseDisabled = errors.New("frame inverse disabled")
...
```

**Comment by jaffee** [comment]
Mostly I just get annoyed when I have to grep for the error string, and then grep again for the error constant to find out where it's actually used. 

A more legitimate complaint is that when the constant error is triggered by another error, that information is lost, and I feel that a more sophisticated error which includes that information is warranted. 

In short, don't hide the actual error if it might be valuable by returning a constant predefined error. Otherwise, returning the constant is fine, and the next level up will wrap it, and that's fine, and if anything needs to match against its value, then it can use `errors.Cause`

However, if some code needs to match against a specific error higher in the stack and we aren't just using a simple constant error, we may have to do something more sophisticated. Cheney's post talks about asserting for behavior (e.g. if error satisfies an `isTemporary` interface) rather than a specific value, and I like this approach, but would need to do a bit more research to clearly define a path forward.

The other need for pre-defined error messages is in client/server communication when a client needs to make a decision based on the specific error. I think that for the human side of things, passing the "condensed stacktrace" error message back to the client is just fine.

Client/server error codes is a subject for a different proposal IMO (and many probably recall our previous discussions on this issue). Right now, for example, we appear to be using HTTP status 409 to denote that an index exists when attempting to create one. Is this OK? Do we want not to rely on HTTP? Again, I think we should revisit this in a separate thread.

**Comment by alanbernstein** [comment]
Lesson learned: don't write "partially fixes #XXX"
