### ISSUE TITLE
Stop using `go get` to fetch source code (in docs).

### ISSUE THREAD

**Issue by jaffee** [pilosa/general#29]
Since all of our projects have (or should have) Makefiles which use `dep` to fetch dependencies, using `go get` is really just a lazy way to clone the repository that also clones all the dependencies thereby polluting the GOPATH. We should replace instances of `go get` in our docs with `git clone <project>.git $GOPATH/src/github.com/pilosa/<project>`

Note: Even when using the `-d` option to stop from installing, dependencies are still cloned. I could not find an option that just clones the project repository.

**Comment by alanbernstein** [comment]
fixed in https://github.com/pilosa/pilosa/pull/1164
