### ISSUE TITLE
Cross-version compatibility test

### ISSUE THREAD

**Issue by codysoyland** [pilosa/general#31]
It would be nice to have an integration test for cross-version compatibility.

The test would run from a shell script, which does the following:

1. Create a new Pilosa cluster with a specified version (passed with a flag).
2. Import data containing:
   a. All three types of containers (Array, Run, Bitmap)
   b. Spans across multiple slices/nodes.
   c. BSI fields
3. Perform a list of queries, contained in `queries.txt`, and write their output to `results-v0.8.txt` (replace version number as appropriate).
4. Shut down cluster and bring up new cluster with another specified version (most likely master or latest release), pointed at existing data files.
5. Run same queries as performed in step 3, except now with the new version, and write the output to `results-v0.9.txt` (or other version).
6. Display the diff output, e.g. `diff results-v0.8.txt results-v0.9.txt`, or "Success" if the diff is empty (nominal case).

**Comment by tgruben** [comment]
I would like to save the length time of each query and report anything "significant".

**Comment by jaffee** [comment]
(Eventually) exercise various API options - different frame types, ranking types, time quantums, etc.
