### ISSUE TITLE
add tests to all projects for building on 32 bit architectures

### ISSUE THREAD

**Issue by jaffee** [pilosa/general#32]
`GOARCH=386 go build` should do the trick. We recently got a report that the PDK was failing to build on 32 bit architectures.

**Comment by yuce** [comment]
Added a step in the CI config of the Go client to run 32bits tests: https://github.com/pilosa/go-pilosa/pull/129

**Comment by yuce** [comment]
Added a similar step to the server's CI config: https://github.com/pilosa/pilosa/pull/1225
