### ISSUE TITLE
Add OCI GoldenGate support 

### ISSUE THREAD

**Issue by travisturner** [pilosa/general#35]
We currently have [kafka support](https://github.com/pilosa/pdk/tree/master/kafka) in the pdk. We need to add support for Oracle GoldenGate as well. This doesn't necessarily need to be part of the pdk (e.g. it may not be written in go), but it needs to be available and documented.

**Comment by jaffee** [comment]
https://www.pilosa.com/blog/writing-a-custom-handler-for-goldengate/
